version: '3'

services:
  dic_frontend:
    image: apinyarr/dic-frontend:v1.0
    deploy:
      mode: replicated
      replicas: 2
    ports:
      - 8080
    restart: always
    environment:
      - BACKEND_URL=http://host.docker.internal:8088/search
  nginx:
    image: nginx:1.25.3-alpine3.18
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - dic_frontend
    ports:
      - "8080:8080"
