apiVersion: v1
kind: ConfigMap
metadata:
  name: dic-config
  namespace: dictionary-namespace
data:
  backend_url: http://dic-backend-service:8088/search
  mongodb_host: dic-mongodb-service
  mongodb_port: "27017"